import React from 'react';
import Head from 'next/head';
import Footer from '../footer/footer.component';

type Props = {
  title?: string;
  children?: JSX.Element[];
};

const defaultTitle =
  'Sa Marchesa - Fiore Sardo e pecorini a latte crudo e naturali';

const LayoutDefault = ({
  children,
  title = defaultTitle,
}: Props): JSX.Element => (
  <div className='layout-default'>
    <Head>
      <title>
        {defaultTitle} {title !== '' ? `| ${title}` : ''}
      </title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.png' />
    </Head>

    <main>{children}</main>
    <Footer />
  </div>
);

export default LayoutDefault;
